### ISSUE TITLE
Cannot find module '@glimmer/syntax' with ember 2.16.2

### ISSUE THREAD

**Issue by mk-conn** [martndemus/ember-font-awesome#185]
I was upgrading from 2.15 to the latest ember-cli/ember/-data versions and this error comes up: 
```
Cannot find module '@glimmer/syntax'
Error: Cannot find module '@glimmer/syntax'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mk/PhpstormProjects/larafum/resources/assets/frontend/node_modules/ember-font-awesome/lib/ast-transform.js:4:22)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

**Comment by nag5000** [comment]
├── ember-cli@2.17.1 
├── ember-data@2.17.0 
└── ember-source@2.17.0 
work with ember-font-awesome@4.0.0-rc.1

**Comment by st-h** [comment]
that's interesting. I was having that issue with 4.0.0-rc.1 a few days ago. Downgraded to 4.0.0 alpha and removed ember-cli-release as that seemed to cause some other issues and everything was good again. After reading your message I switched to 4.0.0-rc.1 again and everything is still working fine. Just adding this here as maybe this is related to the usage of ember-cli-release and might be helpful while debugging.

**Comment by cibernox** [comment]
I'm going to check it today.

**Comment by buschtoens** [comment]
#196 was merged and released as [`v4.0.0-rc.2`](https://github.com/martndemus/ember-font-awesome/releases/tag/v4.0.0-rc.2). Pleas give it a try. :smiley:
